#ifndef __COMPILER_CHECK_ERROR_H
#define __COMPILER_CHECK_ERROR_H

#include "AzureIOTSDKConfig.h"
#include "FreeRTOSConfig.h"

#if NUMBER_CONFIGHEAPSIZE<RTOS_MINIMUM_MARGIN || (((AZURERUNEXAMPLE_STACKSIZE*RTOS_SIZE_STACKMINIMUM)+(AZURETHREADAPI_MAX_TASK_NUMBER*AZURETHREADAPI_STACKSINGLETASK*RTOS_SIZE_STACKMINIMUM)+(AZUREHTTP_MAX_NUMBER_SOCKET*AZURESOCKET_NUMBERBYTES_SINGLESOCKETRECEIVE))>(NUMBER_CONFIGHEAPSIZE-RTOS_MINIMUM_MARGIN))
#error "AZURE IOT SDK Config Error: The preliminary required RTOS Stack is too big for the OS characteristics. Check the AzureIOTSDKConfig.h defines"
#endif

#endif
